- name: Deploy on EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
      docker stop flask || true
      docker rm flask || true
      docker run -d -p 80:5000 --name flask ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
