name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d759bi0ule4c73fgqsm0?key=YOUR_RENDER_KEY"

      - name: List Running Containers (debug only)
        run: docker ps
